### ISSUE TITLE
feature request: support new token-based EC2 metadata service

### ISSUE THREAD

**Issue by kevinburke1** [segmentio/chamber#241] opened 2019-11-22 01:34 UTC
Hi,
AWS released a new version of the EC2 metadata service that uses tokens to authenticate. Along with this, they launched an option to disable the old, unauthenticated credential service for all software running on an EC2 instance. You can read about it here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

It would be good if Chamber could use the new metadata service so then I could disable the old metadata service.

Can you verify that Chamber uses the new EC2 metadata service? If not, can you upgrade the software to use the new EC2 metadata service?

Thanks, Kevin

**Comment by eculver** [comment] 2019-11-22 17:32
Thanks for the prompt. We definitely need to make changes to support the
new metadata API but it should be minimal.

**Comment by ohookins** [comment] 2023-01-24 23:12
Any progress on this? It's becoming quite an issue for security.

**Comment by ohookins** [comment] 2023-01-25 00:39
Actually it seems like the Go SDK version now included actually supports IMDSv2, and I can confirm that it works on instances with IMDSv2 tokens required, so perhaps this is fixed since a while.

**Comment by mckern** [comment] 2023-05-12 01:14
Closing; we may reopen this if we find there's work left to do in this space.

**Closed by mckern** 2023-05-12 01:14 UTC
Labels: enhancement

**Comment by altonotch** [comment] 2024-02-22 15:02
I have a server where IMDSv2 is set to required. Chamber 2.10.3 stopped working. I downloaded the latest version 2.14.0 and tried using it, however, it also failed with the same error:
```
Error: Failed to list store contents: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
