### ISSUE TITLE
Import should lowercase all keys

### ISSUE THREAD

**Issue by skorfmann** [segmentio/chamber#160] opened 2018-10-16 14:22 UTC
When importing a JSON file with uppercase keys, they are imported as is. If I write a key via `chamber write`, the key is lowercased. This leads to duplicated keys. Plus, it breaks the read / delete command, since it apparently assumes lowercased keys.

**Comment by spider-network** [comment] 2018-10-19 08:09
+1

**Comment by ttheune** [comment] 2018-11-14 14:45
Which leads to the question, how does one clean up uppercase keys?

**Comment by skorfmann** [comment] 2018-11-14 15:41
> Which leads to the question, how does one clean up uppercase keys?

I think we just exported the keys, changed them manually and imported them again :)

**Comment by ttheune** [comment] 2018-11-14 16:00
> > Which leads to the question, how does one clean up uppercase keys?
> 
> I think we just exported the keys, changed them manually and imported them again :)

Which gives me duplicates, I'm trying to remove the old UPPERCASE entirely to resolve ENV confusion.  
Is the best practice here to go into SSM manually and clean it up? (And any old services etc etc?)

**Comment by aharasta-earnup** [comment] 2018-11-20 23:53
What's the motivation behind lowercasing all of the keys? Environment variables are commonly represented as all uppercase and it makes it easier to read the actual config key names when visually parsing through Parameter Store on AWS Console.

**Comment by af6140** [comment] 2019-01-08 19:46
Agree with @aharasta-earnup , we use aws-env to export environment variables, write convert all key to lower cases, not expected behavior.

**Comment by terrancej** [comment] 2019-02-28 19:05
bump

**Comment by nickatsegment** [comment] 2019-03-06 21:54
Considering this would be breaking behaviour, targeting for chamber 3.

**Comment by eyablonowitz** [comment] 2019-03-07 15:09
@nickatsegment are you saying that #162 is breaking solely because of the below?

> Modify import to fail an import payload when mixed case keys are provided except when the --case-sensitive switch is passed 

Having been hit by this bug it feels like the breaking behaviour is already present and the changes in #162 are a minimally invasive fix?  If you disagree and want to push to v3 would you consider accepting #162 into v2 if the imports change warned instead of failing?

**Comment by nickatsegment** [comment] 2019-03-12 00:54
Hm, I think my strategy is to accept #162 (pending the docs and tests I was looking for), and target a "real" fix at the model level for v3. Obviously case sensitivity is a thing we have to deal with (if not outright support in the TF_VAR case) and I'd like to deal with it in the core design.

**Comment by ipmb** [comment] 2019-11-07 00:02
For anyone else hitting this, you can remove the uppercased keys with the `awscli`:

```bash
aws ssm delete-parameters --name "{service}/{KEY}"
```

**Comment by wendtek** [comment] 2021-06-29 16:58
Looks like there hasn't been much movement on this in a while. Is any help needed to push it along? It is still greatly affecting usability of the tool for me.

**Comment by alecjacobs5401** [comment] 2023-02-28 16:10
As of https://github.com/segmentio/chamber/releases/tag/v2.12.0, this can now be resolved with
```
chamber import --normalize-keys
```

[Some more details in the README](https://github.com/segmentio/chamber#importing)

This should provide the expected functionality in a non-breaking manner. In a future version, it is likely that this becomes the default behavior

**Comment by mckern** [comment] 2023-05-12 01:13
Closing; still attached to the [v3.0 milestone](https://github.com/segmentio/chamber/milestone/1) and may be revisited in the future.

**Closed by mckern** 2023-05-12 01:13 UTC
Labels: bug
